# Generated by Django 4.2.23 on 2025-08-27 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('playing', 'Playing'), ('played', 'Played'), ('skipped', 'Skipped')], default='queued', max_length=10)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.song')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
            options={
                'ordering': ['-is_paid', 'queued_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrentlyPlaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('queue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_queue.queueitem')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
        ),
    ]
